language: smalltalk
sudo: false

services: mongodb

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-7.0
  
matrix:
  include: 
    - smalltalk_config: .server.ston
    - smalltalk_config: .failingTests.ston
  allow_failures: # Allow bleeding edge builds to fail
    - smalltalk_config: .server.ston
    - smalltalk_config: .failingTests.ston
# configuration
before_script:
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'cargo-ci@travis-ci.org'
